classdef Twlc_Lc_fixed < BasicFdFitModel

    methods

        function [self] = Twlc_Lc_fixed()
            self.dependentVariable   = 'F';
            self.independentVariable = 'd';

            self.fitParams = struct(...
                                  'Lp',     BasicFdFitModel.default_Lp ...
                                , 'S',      BasicFdFitModel.default_S ...
                                , 'g0',     BasicFdFitModel.default_g0 ...
                                , 'g1',     BasicFdFitModel.default_g1 ...
                                );

            self.fixedParams = struct(...
                                  'Lc',     BasicFdFitModel.default_Lc ...
                                , 'C',      BasicFdFitModel.default_C ...
                                , 'Fc',     BasicFdFitModel.default_Fc ...
                                );
        end

        function [fun] = getFitFun(self)
            fun = ...
                @(Lp, S, g0, g1, x) ftWLCInv(...
                                        x, Lp, self.fixedParams.Lc, ...
                                        S, self.fixedParams.C, ...
                                        g0, g1, self.fixedParams.Fc ...
                                        ) ...
                ;
        end

        function [fd_fit] = validateData(self, fd)
            fd_fit = fd;
            if max(fd.f) < self.fixedParams.Fc
                % Error if fitting tWLC with too little data.
                error('fitfd:NotEnoughForceData', ...
                    ['Fitting tWLC with dataset that does not include any ' ...
                     'forces above Fc (Fc = %g pN); result will be ill-defined.'], ...
                    args.Fc);
            end
        end

    end

end
