classdef Figure4_S < Figure4
    % Version of Figure4 showing sweeps of "S" instead of Lp. This is a
    % Supplementary Figure.

    methods

        function [self] = Figure4_S(varargin)
            self = self@Figure4(...
                  'simulS',                     1750 ...
                , 'plotParam',                  'S' ...
                , 'sweepStep',                  0.02 ...
                , 'YLims',                      [0 5000] ...
                , 'randomSeed',                 1977 ...
                , varargin{:} ...
                );
        end

    end

end
